name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build:all

    - name: Generate changelog
      id: changelog
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Generate changelog from commits (handle case where no previous tag exists)
        if git describe --tags --abbrev=0 HEAD^ 2>/dev/null; then
          CHANGELOG=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD)
        else
          CHANGELOG=$(git log --pretty=format:"- %s")
        fi
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release v${{ steps.changelog.outputs.version }}
        body: |
          ## Changes in v${{ steps.changelog.outputs.version }}
          
          ${{ steps.changelog.outputs.changelog }}
          
          ## Installation
          
          ### NPM
          ```bash
          npm install lucid-alerts@${{ steps.changelog.outputs.version }}
          ```
          
          ### CDN
          ```html
          <script src="https://cdn.jsdelivr.net/npm/lucid-alerts@${{ steps.changelog.outputs.version }}/dist/lucid-alerts.min.js"></script>
          ```
        draft: false
        prerelease: false
        files: |
          dist/lucid-alerts.min.js
          dist/lucid-alerts.js
          dist/lucid-alerts.esm.js
          dist/lucid-alerts.d.ts